SELECT DISTINCT(P.CART_ID)
FROM CART_PRODUCTS P, (SELECT CART_ID FROM CART_PRODUCTS
                       WHERE NAME = 'Yogurt') Y
WHERE P.CART_ID = Y.CART_ID
AND P.NAME = 'Milk'
ORDER BY P.CART_ID;
