SELECT TO_CHAR(SALES_DATE, 'yyyy') "YEAR", EXTRACT(MONTH from SALES_DATE) "MONTH", GENDER, COUNT(DISTINCT(I.USER_ID)) "USERS"
FROM USER_INFO I, ONLINE_SALE S
WHERE I.USER_ID = S.USER_ID
AND I.GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'yyyy'), EXTRACT(MONTH from SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;