SELECT P.PRODUCT_ID, P.PRODUCT_NAME, PRICE * MOUNT AS TOTAL_SALES FROM FOOD_PRODUCT P, 
(SELECT PRODUCT_ID, SUM(AMOUNT) AS MOUNT
FROM FOOD_ORDER
WHERE 1 = 1
AND PRODUCE_DATE BETWEEN TO_DATE('20220501', 'yyyymmdd') AND TO_DATE('20220531', 'yyyymmdd')
GROUP BY PRODUCT_ID) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;