SELECT FLAVOR 
FROM (SELECT J.FLAVOR,SUM(F.TOTAL_ORDER)"S1", SUM(J.TOTAL_ORDER)"S2"
FROM FIRST_HALF F, JULY J
WHERE F.SHIPMENT_ID(+) = J.SHIPMENT_ID
GROUP BY J.FLAVOR
ORDER BY S1 + S2 DESC)
FETCH FIRST 3 ROW ONLY;