SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME,A.APNT_YMD
FROM APPOINTMENT A, DOCTOR D, PATIENT P
WHERE A.PT_NO = P.PT_NO
AND A.MDDR_ID = D.DR_ID
AND TO_CHAR(A.APNT_YMD, 'yyyy-mm-dd') = '2022-04-13' 
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;